language: python

python:
- '3.4'

env:
- DJANGO=Django>=1.9

install:
- pip install coveralls -r requirements-dev.txt

script:
- flake8 democracy
- py.test -vvv --cov democracy democracy/tests

after_success:
  coveralls
