language: python

python:
- '3.4'

env:
- DJANGO=Django>=1.8

install:
- pip install coveralls -r requirements.txt

script:
- flake8 democracy
- py.test -vvv --cov democracy democracy/tests

after_success:
  coveralls
