---
- name: Create base image
  hosts: localhost
  tasks:
  - name: Create container for building image
    docker_container:
      name: kerrokantasi_builder
      image: python:3.6
      interactive: true
      hostname: kerrokantasi-api
      state: started
      recreate: "{{ recreate_image|default(true) }}"
  - name: Add container to dynamic inventory
    add_host:
      name: kerrokantasi_builder
      ansible_connection: docker
      ansible_user: root

- name: Build kerrokantasi in container
  hosts: kerrokantasi_builder
  become: yes
  become_method: su
  vars_files:
    - ansible/kerrokantasi-api-build-config.yml
  roles:
    - django-configuration
    - python-container
  tasks:
    - name: Insert entrypoint into docker_container
      copy:
        src: ansible/files/docker-entrypoint.sh
        dest: /docker-entrypoint.sh
        mode: 0755

- name: Finalize container
  hosts: localhost
  tasks:
    - name: Commit and define entrypoint in image
      become: no
      local_action: command docker commit --change "ENTRYPOINT /docker-entrypoint.sh" kerrokantasi_builder helsinki/kerrokantasi-api
    - name: Destroy the build container
      docker_container:
        name: kerrokantasi_builder
        state: absent
