trigger: none

pr:
  branches:
    include:
      - master

pool: Default

resources:
  repositories:
  # Azure repository reference
  - repository: kerrokantasi-pipelines
    type: git
    name: kerrokantasi/kerrokantasi-pipelines
    ref: refs/heads/api-linting

extends:
  template: azure-pipelines-build-kerrokantasi-api-pr.yml@kerrokantasi-pipelines
