[tool.black]
extend-exclude = "migrations"
line_length = 120

[tool.isort]
profile = "black"
py_version = 38
atomic = true
extend_skip_glob = ["*migrations*"]
line_length = 120
known_first_party = "democracy"
known_standard_library = ["token", "tokenize"]
known_third_party = ["django"]
