# Generated by Django 1.9 on 2015-12-03 12:21
from __future__ import unicode_literals

import democracy.enums
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import enumfields.fields
import jsonfield.fields
from enumfields import Enum


class SectionType(Enum):
    INTRODUCTION = "introduction"
    PLAIN = "plain"
    SCENARIO = "scenario"
    AREA = "area"
    CLOSURE_INFO = "closure info"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of last modification')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('id', models.CharField(blank=True, help_text='You may leave this empty to automatically generate an ID', max_length=32, primary_key=True, serialize=False, verbose_name='identifier')),
                ('n_comments', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Number of comments')),
                ('commenting', enumfields.fields.EnumIntegerField(default=0, enum=democracy.enums.Commenting)),
                ('open_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='opening time')),
                ('close_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='closing time')),
                ('force_closed', models.BooleanField(default=False, verbose_name='force hearing closed')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='abstract')),
                ('borough', models.CharField(blank=True, default='', max_length=200, verbose_name='borough')),
                ('servicemap_url', models.CharField(blank=True, default='', max_length=255, verbose_name='service map URL')),
                ('latitude', models.FloatField(null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='longitude')),
                ('geojson', jsonfield.fields.JSONField(blank=True, editable=False, null=True, verbose_name='GeoJSON object')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearing_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('followers', models.ManyToManyField(blank=True, editable=False, related_name='followed_hearings', to=settings.AUTH_USER_MODEL, verbose_name='users who follow this hearing')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HearingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of last modification')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('author_name', models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='author name')),
                ('n_votes', models.IntegerField(default=0, editable=False, verbose_name='number of votes given to this comment')),
                ('n_legacy_votes', models.IntegerField(default=0, verbose_name='number of votes imported from legacy system')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearingcomment_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='democracy.Hearing')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearingcomment_modified', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_democracy_hearingcomment', to=settings.AUTH_USER_MODEL, verbose_name='users who voted for this comment')),
            ],
            options={
                'abstract': False,
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='HearingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of last modification')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('caption', models.TextField(blank=True, default='', verbose_name='caption')),
                ('height', models.IntegerField(default=0, editable=False, verbose_name='height')),
                ('width', models.IntegerField(default=0, editable=False, verbose_name='width')),
                ('image', models.ImageField(height_field='height', upload_to='images/%Y/%m', verbose_name='image', width_field='width')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearingimage_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='democracy.Hearing')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearingimage_modified', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
            ],
            options={
                'abstract': False,
                'ordering': ('ordering', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of last modification')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('label', models.CharField(default='', max_length=200, verbose_name='label')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_modified', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of last modification')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('id', models.CharField(blank=True, help_text='You may leave this empty to automatically generate an ID', max_length=32, primary_key=True, serialize=False, verbose_name='identifier')),
                ('n_comments', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Number of comments')),
                ('commenting', enumfields.fields.EnumIntegerField(default=0, enum=democracy.enums.Commenting)),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('type', enumfields.fields.EnumField(default='plain', enum=SectionType, max_length=10, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('abstract', models.TextField(blank=True, verbose_name='abstract')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('hearing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='democracy.Hearing')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_modified', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='SectionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of last modification')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('author_name', models.CharField(blank=True, editable=False, max_length=40, null=True, verbose_name='author name')),
                ('n_votes', models.IntegerField(default=0, editable=False, verbose_name='number of votes given to this comment')),
                ('n_legacy_votes', models.IntegerField(default=0, verbose_name='number of votes imported from legacy system')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectioncomment_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectioncomment_modified', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='democracy.Section')),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_democracy_sectioncomment', to=settings.AUTH_USER_MODEL, verbose_name='users who voted for this comment')),
            ],
            options={
                'abstract': False,
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='time of creation')),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='time of last modification')),
                ('published', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='title')),
                ('caption', models.TextField(blank=True, default='', verbose_name='caption')),
                ('height', models.IntegerField(default=0, editable=False, verbose_name='height')),
                ('width', models.IntegerField(default=0, editable=False, verbose_name='width')),
                ('image', models.ImageField(height_field='height', upload_to='images/%Y/%m', verbose_name='image', width_field='width')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='ordering')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionimage_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionimage_modified', to=settings.AUTH_USER_MODEL, verbose_name='last modified by')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='democracy.Section')),
            ],
            options={
                'abstract': False,
                'ordering': ('ordering', 'title'),
            },
        ),
        migrations.AddField(
            model_name='hearing',
            name='labels',
            field=models.ManyToManyField(blank=True, to='democracy.Label', verbose_name='labels'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearing_modified', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
    ]
