# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 11:29
from __future__ import unicode_literals

import democracy.enums
from django.conf import settings
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hearing',
            options={'verbose_name': 'hearing', 'verbose_name_plural': 'hearings'},
        ),
        migrations.AlterModelOptions(
            name='hearingcomment',
            options={'verbose_name': 'hearing comment', 'verbose_name_plural': 'hearing comments'},
        ),
        migrations.AlterModelOptions(
            name='hearingimage',
            options={'verbose_name': 'hearing image', 'verbose_name_plural': 'hearing images'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'label', 'verbose_name_plural': 'labels'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['ordering'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='sectioncomment',
            options={'verbose_name': 'section comment', 'verbose_name_plural': 'section comments'},
        ),
        migrations.AlterModelOptions(
            name='sectionimage',
            options={'verbose_name': 'section image', 'verbose_name_plural': 'section images'},
        ),
        migrations.AlterField(
            model_name='hearing',
            name='commenting',
            field=enumfields.fields.EnumIntegerField(default=0, enum=democracy.enums.Commenting, verbose_name='commenting'),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='followers',
            field=models.ManyToManyField(blank=True, editable=False, help_text='users who follow this hearing', related_name='followed_hearings', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='n_comments',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='hearingcomment',
            name='n_legacy_votes',
            field=models.IntegerField(default=0, editable=False, help_text='number of votes imported from legacy system', verbose_name='legacy vote count'),
        ),
        migrations.AlterField(
            model_name='hearingcomment',
            name='n_votes',
            field=models.IntegerField(default=0, editable=False, help_text='number of votes given to this comment', verbose_name='vote count'),
        ),
        migrations.AlterField(
            model_name='hearingcomment',
            name='voters',
            field=models.ManyToManyField(blank=True, help_text='users who voted for this comment', related_name='voted_democracy_hearingcomment', to=settings.AUTH_USER_MODEL, verbose_name='voters'),
        ),
        migrations.AlterField(
            model_name='section',
            name='commenting',
            field=enumfields.fields.EnumIntegerField(default=0, enum=democracy.enums.Commenting, verbose_name='commenting'),
        ),
        migrations.AlterField(
            model_name='section',
            name='n_comments',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='number of comments'),
        ),
        migrations.AlterField(
            model_name='sectioncomment',
            name='n_legacy_votes',
            field=models.IntegerField(default=0, editable=False, help_text='number of votes imported from legacy system', verbose_name='legacy vote count'),
        ),
        migrations.AlterField(
            model_name='sectioncomment',
            name='n_votes',
            field=models.IntegerField(default=0, editable=False, help_text='number of votes given to this comment', verbose_name='vote count'),
        ),
        migrations.AlterField(
            model_name='sectioncomment',
            name='voters',
            field=models.ManyToManyField(blank=True, help_text='users who voted for this comment', related_name='voted_democracy_sectioncomment', to=settings.AUTH_USER_MODEL, verbose_name='voters'),
        ),
    ]
