# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 14:53
from __future__ import unicode_literals

import democracy.enums
from django.db import migrations
import enumfields.fields
from enumfields import Enum


class SectionType(Enum):
    INTRODUCTION = "introduction"
    PLAIN = "plain"
    SCENARIO = "scenario"
    AREA = "area"
    CLOSURE_INFO = "closure info"


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0003_usability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=enumfields.fields.EnumField(default='plain', enum=SectionType, max_length=64, verbose_name='type'),
        ),
    ]
