# Generated by Django 1.9.2 on 2016-02-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class SectionType:
    INTRODUCTION = "introduction"
    PLAIN = "plain"
    SCENARIO = "scenario"
    AREA = "area"
    CLOSURE_INFO = "closure info"


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0003_usability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="type",
            field=models.CharField(default="plain", max_length=64, verbose_name="type"),
        ),
    ]
