# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:39
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0005_lengthen_author_name_and_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='hearing',
            name='geojson',
            field=djgeojson.fields.GeometryField(blank=True, null=True, verbose_name='area'),
        ),
    ]
