# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0007_section_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearingcomment',
            name='plugin_data',
            field=models.TextField(blank=True, verbose_name='plugin data'),
        ),
        migrations.AddField(
            model_name='hearingcomment',
            name='plugin_identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='plugin identifier'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='plugin_data',
            field=models.TextField(blank=True, verbose_name='plugin data'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='plugin_identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='plugin identifier'),
        ),
    ]
