# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 09:31
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0013_unique_hearing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hearing',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='You may leave this empty to automatically generate a slug', populate_from='title', unique=True, verbose_name='slug'),
        ),
    ]
