# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 13:18
from __future__ import unicode_literals

from django.core.management.base import CommandError
from django.db import migrations


def forwards(apps, schema_editor):
    """
    Convert Hearing images to introduction Section images
    """
    hearing_images = apps.get_model('democracy', 'HearingImage').objects.all()
    section_image_model = apps.get_model('democracy', 'SectionImage')

    for hearing_image in hearing_images:
        data = {field: getattr(hearing_image, field) for field in ('title', 'caption', 'height', 'width', 'image',
                                                                   'ordering', 'created_by', 'created_at',
                                                                   'modified_at', 'modified_by')}

        section = hearing_image.hearing.sections.filter(type__identifier='introduction').first()
        if not section:
            raise CommandError("Hearing '%s' has HearingImage(s) but not an introduction section for those." %
                               hearing_image.hearing_id)

        data['section'] = section
        section_image_model.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0016_merge_comments'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='hearingimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hearingimage',
            name='hearing',
        ),
        migrations.RemoveField(
            model_name='hearingimage',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='HearingImage',
        ),
    ]
