# Generated by Django 1.9.2 on 2016-05-27 07:56
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    """
    Set empty intro section abstract based on Hearing abstract
    """
    hearing_model = apps.get_model('democracy', 'Hearing')

    for hearing in hearing_model.objects.exclude(abstract=''):
        intro_sections = hearing.sections.filter(type__identifier='introduction', abstract='')

        for intro_section in intro_sections:
            intro_section.abstract = hearing.abstract
            intro_section.save(update_fields=('abstract',))


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0018_remove_hearing_commenting'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='hearing',
            name='abstract',
        ),

    ]
