# Generated by Django 1.9.2 on 2016-06-08 16:46
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("democracy", "0020_rename_intro_section_to_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of last modification",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="public"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name="deleted",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifier",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("phone", models.CharField(max_length=50, verbose_name="phone")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactperson_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactperson_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="last modified by",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="democracy.Organization",
                        verbose_name="organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contact persons",
                "verbose_name": "contact person",
            },
        ),
        migrations.AddField(
            model_name="hearing",
            name="contact_persons",
            field=models.ManyToManyField(
                related_name="hearings",
                to="democracy.ContactPerson",
                verbose_name="contact persons",
            ),
        ),
    ]
