# Generated by Django 1.9.2 on 2016-06-20 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0021_add_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectioncomment",
            name="author_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="author name"
            ),
        ),
    ]
