# Generated by Django 1.9.6 on 2016-09-15 12:32
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("democracy", "0022_comment_author_name_editable"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of creation",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="time of last modification",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="public"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        editable=False,
                        verbose_name="deleted",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "caption",
                    models.TextField(blank=True, default="", verbose_name="caption"),
                ),
                (
                    "height",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="height"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="width"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height",
                        upload_to="images/%Y/%m",
                        verbose_name="image",
                        width_field="width",
                    ),
                ),
                (
                    "ordering",
                    models.IntegerField(
                        db_index=True,
                        default=1,
                        help_text="The ordering position for this object. Objects with smaller numbers appear first.",
                        verbose_name="ordering",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "comment images",
                "verbose_name": "comment image",
            },
        ),
        migrations.AlterModelOptions(
            name="sectioncomment",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "section comment",
                "verbose_name_plural": "section comments",
            },
        ),
        migrations.AddField(
            model_name="sectioncomment",
            name="geojson",
            field=djgeojson.fields.GeometryField(
                blank=True, null=True, verbose_name="location"
            ),
        ),
        migrations.AddField(
            model_name="commentimage",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="democracy.SectionComment",
            ),
        ),
        migrations.AddField(
            model_name="commentimage",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentimage_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="commentimage",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentimage_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="last modified by",
            ),
        ),
    ]
