# Generated by Django 1.9.6 on 2016-10-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0024_add_label_to_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectioncomment",
            old_name="n_legacy_votes",
            new_name="n_unregistered_votes",
        ),
        migrations.AlterField(
            model_name="sectioncomment",
            name="n_unregistered_votes",
            field=models.IntegerField(
                default=0,
                help_text="number of unregistered votes",
                verbose_name="unregistered vote count",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="voting",
            field=models.IntegerField(default=1, verbose_name="voting"),
        ),
    ]
