# Generated by Django 1.9.6 on 2016-10-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0025_add_unregistered_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='plugin_iframe_url',
            field=models.URLField(blank=True, verbose_name='plugin iframe url'),
        ),
    ]
