# Generated by Django 1.9.13 on 2017-07-21 11:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0033_add_n_votes_to_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="democracy.Organization",
            ),
        ),
    ]
