# Generated by Django 1.11.10 on 2018-03-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0039_add_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearing',
            name='project_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hearings', to='democracy.ProjectPhase', verbose_name='project phase'),
        ),
    ]
