# Generated by Django 1.11.10 on 2018-02-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0041_add_file_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfile',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='democracy.Section'),
        ),
    ]
