# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 09:28
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0042_sectionfile_section_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfile',
            name='uploaded_file',
            field=models.FileField(max_length=2048, storage=django.core.files.storage.FileSystemStorage(location='/home/heikkjus/code/helsinki/kerrokantasi/var/protected'), upload_to='files/%Y/%m', verbose_name='file'),
        ),
    ]
