# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0043_basefile_filename_max_len'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionfile',
            old_name='uploaded_file',
            new_name='file',
        ),
    ]
