# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 10:39
from __future__ import unicode_literals

import democracy.enums
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0044_rename_uploaded_file_to_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionpoll',
            options={'ordering': ['ordering'], 'verbose_name': 'section poll', 'verbose_name_plural': 'section polls'},
        ),
        migrations.AlterModelOptions(
            name='sectionpolloption',
            options={'ordering': ['ordering'], 'verbose_name': 'section poll option', 'verbose_name_plural': 'section poll options'},
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='democracy.SectionComment'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='commenting',
            field=enumfields.fields.EnumIntegerField(default=0, enum=democracy.enums.Commenting, verbose_name='commenting'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='n_comments',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='number of comments'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='voting',
            field=enumfields.fields.EnumIntegerField(default=1, enum=democracy.enums.Commenting, verbose_name='voting'),
        ),
        migrations.AlterField(
            model_name='sectionfile',
            name='file',
            field=models.FileField(max_length=2048, storage=django.core.files.storage.FileSystemStorage(location='/Users/riku/Dropbox/Tyo/kerrokantasi/var/protected'), upload_to='files/%Y/%m', verbose_name='file'),
        ),
    ]
