# Generated by Django 1.11.20 on 2019-06-05 19:28
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0046_add_n_comments_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncomment',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='democracy.Organization'),
        ),
        migrations.AddField(
            model_name='sectioncomment',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
