# Generated by Django 1.11.21 on 2019-07-02 15:30
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0048_add_sectioncomment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimagetranslation',
            name='alt_text',
            field=models.TextField(blank=True, default='', verbose_name='alt text'),
        ),
    ]
