# Generated by Django 2.2.12 on 2020-08-13 11:12

import django.core.files.storage
import django.db.models.deletion
import parler.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0052_auto_20200401_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpersontranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.ContactPerson",
            ),
        ),
        migrations.AlterField(
            model_name="hearingtranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.Hearing",
            ),
        ),
        migrations.AlterField(
            model_name="labeltranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.Label",
            ),
        ),
        migrations.AlterField(
            model_name="projectphasetranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.ProjectPhase",
            ),
        ),
        migrations.AlterField(
            model_name="projecttranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.Project",
            ),
        ),
        migrations.AlterField(
            model_name="sectionfile",
            name="file",
            field=models.FileField(
                max_length=2048,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/srv/kerrokantasi/user_uploads"
                ),
                upload_to="files/%Y/%m",
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="sectionfiletranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.SectionFile",
            ),
        ),
        migrations.AlterField(
            model_name="sectionimagetranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.SectionImage",
            ),
        ),
        migrations.AlterField(
            model_name="sectionpolloptiontranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.SectionPollOption",
            ),
        ),
        migrations.AlterField(
            model_name="sectionpolltranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.SectionPoll",
            ),
        ),
        migrations.AlterField(
            model_name="sectiontranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="democracy.Section",
            ),
        ),
    ]
