# Generated by Django 2.2.12 on 2021-02-15 11:38

import django.contrib.gis.db.models.fields
import django.core.files.storage
from django.db import migrations, models
from django.contrib.gis.geos import GEOSGeometry, GeometryCollection
import json


def get_geometry_from_geojson(geojson):
    gc = GeometryCollection()
    if geojson is None:
        return None

    geometry_data = geojson.get('geometry', None) or geojson
    geometry = GEOSGeometry(json.dumps(geometry_data))
    gc.append(geometry)

    return gc


def hearings_geometry_migration(apps, schema_editor):
    Hearing = apps.get_model('democracy', 'Hearing')
    for hearing in Hearing.objects.filter(geojson__isnull=False):
        hearing.geometry = get_geometry_from_geojson(hearing.geojson)
        hearing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0053_auto_20200813_1112'),
    ]

    operations = [
        migrations.RunPython(hearings_geometry_migration),
        migrations.AlterField(
            model_name='hearing',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326, verbose_name='area geometry'),
        ),
    ]
