# Generated by Django 2.2.20 on 2021-12-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0055_add_deletion_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectioncomment",
            name="delete_reason",
            field=models.TextField(blank=True, verbose_name="delete reason"),
        ),
    ]
