# Generated by Django 2.2.20 on 2021-12-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0057_add_flagged_fields_to_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionpollanswer",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_answers",
                to="democracy.SectionComment",
            ),
        ),
    ]
