# Generated by Django 3.2.23 on 2024-01-17 12:39

import democracy.models.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracy', '0062_edited_moderated_edit_reason_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfile',
            name='file',
            field=models.FileField(max_length=2048, storage=democracy.models.files.ProtectedFileSystemStorage(), upload_to='files/%Y/%m', verbose_name='file'),
        ),
    ]
