# Generated by Django 5.2.5 on 2025-09-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0064_alter_commentimage_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="commenting",
            field=models.IntegerField(
                choices=[
                    (0, "No commenting"),
                    (1, "Registered users only"),
                    (2, "Open commenting"),
                    (3, "Strong authentication only"),
                ],
                default=0,
                verbose_name="commenting",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="commenting_map_tools",
            field=models.IntegerField(
                choices=[(0, "none"), (1, "marker"), (2, "all")],
                default=0,
                verbose_name="commenting_map_tools",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="voting",
            field=models.IntegerField(
                choices=[
                    (0, "No commenting"),
                    (1, "Registered users only"),
                    (2, "Open commenting"),
                    (3, "Strong authentication only"),
                ],
                default=1,
                verbose_name="voting",
            ),
        ),
        migrations.AlterField(
            model_name="sectioncomment",
            name="commenting",
            field=models.IntegerField(
                choices=[
                    (0, "No commenting"),
                    (1, "Registered users only"),
                    (2, "Open commenting"),
                    (3, "Strong authentication only"),
                ],
                default=0,
                verbose_name="commenting",
            ),
        ),
        migrations.AlterField(
            model_name="sectioncomment",
            name="commenting_map_tools",
            field=models.IntegerField(
                choices=[(0, "none"), (1, "marker"), (2, "all")],
                default=0,
                verbose_name="commenting_map_tools",
            ),
        ),
        migrations.AlterField(
            model_name="sectioncomment",
            name="voting",
            field=models.IntegerField(
                choices=[
                    (0, "No commenting"),
                    (1, "Registered users only"),
                    (2, "Open commenting"),
                    (3, "Strong authentication only"),
                ],
                default=1,
                verbose_name="voting",
            ),
        ),
    ]
