# Generated by Django 5.2.9 on 2026-01-09 10:16

import autoslug.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0065_alter_section_commenting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactpersontranslation",
            name="title",
            field=models.CharField(
                help_text="Contact person's job title or role",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="close_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time when the hearing closes for participation",
                verbose_name="closing time",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="force_closed",
            field=models.BooleanField(
                default=False,
                help_text="Manually close the hearing regardless of open/close dates",
                verbose_name="force hearing closed",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="geojson",
            field=djgeojson.fields.GeoJSONField(
                blank=True,
                help_text="Geographic area related to this hearing in GeoJSON format",
                null=True,
                verbose_name="area",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(
                blank=True,
                help_text="PostGIS geometry collection for spatial database queries",
                null=True,
                srid=4326,
                verbose_name="area geometry",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="n_comments",
            field=models.IntegerField(
                blank=True,
                default=0,
                editable=False,
                help_text="Cached total count of all comments across all sections",
                verbose_name="number of comments",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="open_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time when the hearing opens for public participation",
                verbose_name="opening time",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="servicemap_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL to the related location in the service map",
                max_length=255,
                verbose_name="service map URL",
            ),
        ),
        migrations.AlterField(
            model_name="hearing",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=True,
                help_text="URL-friendly identifier. Leave empty to auto-generate from title",
                populate_from="title",
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="hearingtranslation",
            name="borough",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Borough or district where the hearing is located",
                max_length=200,
                verbose_name="borough",
            ),
        ),
        migrations.AlterField(
            model_name="hearingtranslation",
            name="title",
            field=models.CharField(
                help_text="The main title of the hearing",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="labeltranslation",
            name="label",
            field=models.CharField(
                default="",
                help_text="Label for categorizing and filtering hearings",
                max_length=200,
                verbose_name="label",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="identifier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External identifier for system integration",
                max_length=50,
                null=True,
                verbose_name="identifier",
            ),
        ),
        migrations.AlterField(
            model_name="projectphase",
            name="project",
            field=models.ForeignKey(
                help_text="Project this phase belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="democracy.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectphasetranslation",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Detailed description of this project phase",
                max_length=2048,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="projectphasetranslation",
            name="schedule",
            field=models.CharField(
                blank=True,
                help_text="Timeline and schedule information for this phase",
                max_length=2048,
                verbose_name="schedule",
            ),
        ),
        migrations.AlterField(
            model_name="projectphasetranslation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Phase title within the project timeline",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="projecttranslation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Project title for grouping related hearings",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="hearing",
            field=models.ForeignKey(
                help_text="Hearing this section belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sections",
                to="democracy.hearing",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="plugin_data",
            field=models.TextField(
                blank=True,
                help_text="JSON configuration data for the plugin",
                verbose_name="plugin data",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="plugin_fullscreen",
            field=models.BooleanField(
                default=False,
                help_text="Whether the plugin should be displayed in fullscreen mode",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="plugin_identifier",
            field=models.CharField(
                blank=True,
                help_text="Identifier for custom plugin functionality (e.g., map visualization)",
                max_length=255,
                verbose_name="plugin identifier",
            ),
        ),
        migrations.AlterField(
            model_name="sectionfiletranslation",
            name="caption",
            field=models.TextField(
                blank=True,
                default="",
                help_text="File caption or description",
                verbose_name="caption",
            ),
        ),
        migrations.AlterField(
            model_name="sectionfiletranslation",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="File title for identification",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="sectionimagetranslation",
            name="alt_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Alternative text for accessibility and SEO",
                verbose_name="alt text",
            ),
        ),
        migrations.AlterField(
            model_name="sectionimagetranslation",
            name="caption",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Image caption displayed to users",
                verbose_name="caption",
            ),
        ),
        migrations.AlterField(
            model_name="sectionimagetranslation",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Image title for identification",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="sectionpolloptiontranslation",
            name="text",
            field=models.TextField(
                help_text="Poll option choice text", verbose_name="option text"
            ),
        ),
        migrations.AlterField(
            model_name="sectionpolltranslation",
            name="text",
            field=models.TextField(
                help_text="Poll question text displayed to users", verbose_name="text"
            ),
        ),
        migrations.AlterField(
            model_name="sectiontranslation",
            name="abstract",
            field=models.TextField(
                blank=True,
                help_text="Brief summary of the section content",
                verbose_name="abstract",
            ),
        ),
        migrations.AlterField(
            model_name="sectiontranslation",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Main content body of the section (supports rich text)",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="sectiontranslation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Section heading displayed in the hearing",
                max_length=255,
                verbose_name="title",
            ),
        ),
    ]
