# Generated by Django 5.2.17 on 2026-09-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0066_alter_contactpersontranslation_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionimage",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="democracy.section",
            ),
        ),
    ]
