# Generated by Django 5.2.17 on 2026-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0067_nullable_sectionimage_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionimage",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("section_level", "section-level image"),
                    ("inline", "inline image used within section content"),
                ],
                default="section_level",
                help_text="Distinguishes section-level images from images used in section content.",
                max_length=32,
                verbose_name="purpose",
            ),
        ),
    ]
