# Generated by Django 5.2.17 on 2026-09-29 13:30

from django.db import migrations, models

import democracy.utils.image_uploads


class Migration(migrations.Migration):
    dependencies = [
        ("democracy", "0068_sectionimage_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionimage",
            name="image",
            field=models.ImageField(
                height_field="height",
                upload_to=democracy.utils.image_uploads.upload_image_to,
                verbose_name="image",
                width_field="width",
            ),
        ),
    ]
