uwsgi:
  # Needed plugins if running against Debian uwsgi-package
  # python docker image cannot use that due to linker mishaps
  # plugins: python3,http
  wsgi-file: kerrokantasi/wsgi.py
  processes: 3
  #threads: 1
  master: true
  #uid: hauki
  umask: 022
  reload-on-rss: 300
  # Allow large image uploads
  # chunked-input-limit: 10485760
  buffer-size: 32768
  http: :8000
  static-map: /static=/srv/static
  static-map: /media=/srv/media

  # Ignore write errors
  ignore-sigpipe: true
  ignore-write-errors: true
  disable-write-exception: true

  logger-req: stdio
  log-format: '"remote_addr": "%(addr)", "x_forwarded_for":"%(var.HTTP_X_FORWARDED_FOR)", "request_id":"%(var.HTTP_X_REQUEST_ID)", "remote_user":"%(user)", "bytes_sent":%(size), "request_time":%(secs), "status":%(status), "host":"%(host)", "request_proto":"%(proto)", "path":"%(uri)", "request_length":%(cl), "http_referer":"%(referer)", "http_user_agent":"%(uagent)"'
  log-req-encoder: format {"time":"${strftime:%%Y:%%m:%%d %%H:%%M:%%S}", "source":"uwsgi-req", ${msg}}
  log-req-encoder: nl
