# Generated by Django 2.2.10 on 2020-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerrokantasi', '0003_update_helusers_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_strong_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
