# Generated by Django 5.2.7 on 2025-10-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kerrokantasi", "0005_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_api_use",
            field=models.DateField(
                blank=True, null=True, verbose_name="Latest API token usage date"
            ),
        ),
    ]
